2021-03-19 14:02:55,962 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2021-03-19 14:02:58,236 - telegram.ext.updater - WARNING - Exiting immediately!
2021-03-19 14:11:52,148 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2021-03-19 14:12:24,269 - __main__ - WARNING - Update "{'update_id': 79207663, 'inline_query': {'id': '6067064935978454394', 'query': 'angry', 'offset': '', 'from': {'id': 1412598634, 'first_name': 'IVY', 'is_bot': False, 'username': 'I_01010110_Y', 'language_code': 'en'}}, '_effective_user': {'id': 1412598634, 'first_name': 'IVY', 'is_bot': False, 'username': 'I_01010110_Y', 'language_code': 'en'}}" caused error "'Kaomoji' object has no attribute 'angry'"
2021-03-19 14:12:39,722 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2021-03-19 14:12:51,699 - __main__ - WARNING - Update "{'update_id': 79207664, 'inline_query': {'id': '6067064938907902755', 'query': 'angry', 'offset': '', 'from': {'id': 1412598634, 'first_name': 'IVY', 'is_bot': False, 'username': 'I_01010110_Y', 'language_code': 'en'}}, '_effective_user': {'id': 1412598634, 'first_name': 'IVY', 'is_bot': False, 'username': 'I_01010110_Y', 'language_code': 'en'}}" caused error "'Kaomoji' object has no attribute 'angry'"
2021-03-19 14:12:57,119 - __main__ - WARNING - Update "{'update_id': 79207666, 'inline_query': {'id': '6067064935943287617', 'query': 'angry', 'offset': '', 'from': {'id': 1412598634, 'first_name': 'IVY', 'is_bot': False, 'username': 'I_01010110_Y', 'language_code': 'en'}}, '_effective_user': {'id': 1412598634, 'first_name': 'IVY', 'is_bot': False, 'username': 'I_01010110_Y', 'language_code': 'en'}}" caused error "'Kaomoji' object has no attribute 'angry'"
2021-03-19 14:14:07,003 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2021-03-19 14:14:16,092 - __main__ - WARNING - Update "{'update_id': 79207667, 'inline_query': {'id': '6067064936427150917', 'query': 'angry', 'offset': '', 'from': {'id': 1412598634, 'first_name': 'IVY', 'is_bot': False, 'username': 'I_01010110_Y', 'language_code': 'en'}}, '_effective_user': {'id': 1412598634, 'first_name': 'IVY', 'is_bot': False, 'username': 'I_01010110_Y', 'language_code': 'en'}}" caused error "'Kaomoji' object has no attribute 'angry'"
2021-03-19 14:14:24,373 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2021-03-19 14:14:25,269 - telegram.ext.updater - WARNING - Exiting immediately!
2021-03-19 14:15:09,490 - __main__ - WARNING - Update "{'update_id': 79207669, 'inline_query': {'id': '6067064937679007100', 'query': 'angry', 'offset': '', 'from': {'id': 1412598634, 'first_name': 'IVY', 'is_bot': False, 'username': 'I_01010110_Y', 'language_code': 'en'}}, '_effective_user': {'id': 1412598634, 'first_name': 'IVY', 'is_bot': False, 'username': 'I_01010110_Y', 'language_code': 'en'}}" caused error "'Kaomoji' object has no attribute 'angry'"
2021-03-19 14:15:31,737 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2021-03-19 14:15:32,645 - telegram.ext.updater - WARNING - Exiting immediately!
2021-03-19 14:15:41,739 - __main__ - WARNING - Update "{'update_id': 79207670, 'inline_query': {'id': '6067064936645816143', 'query': 'angry', 'offset': '', 'from': {'id': 1412598634, 'first_name': 'IVY', 'is_bot': False, 'username': 'I_01010110_Y', 'language_code': 'en'}}, '_effective_user': {'id': 1412598634, 'first_name': 'IVY', 'is_bot': False, 'username': 'I_01010110_Y', 'language_code': 'en'}}" caused error "'Kaomoji' object has no attribute 'angry'"
2021-03-19 14:16:45,583 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2021-03-19 14:17:30,106 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2021-03-19 14:17:31,111 - telegram.ext.updater - WARNING - Exiting immediately!
2021-03-19 14:21:58,644 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2021-03-19 14:22:05,785 - telegram.ext.updater - WARNING - Exiting immediately!
2021-03-19 14:22:42,581 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2021-03-19 14:22:43,292 - telegram.ext.updater - WARNING - Exiting immediately!
2021-03-19 14:24:03,023 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2021-03-19 14:30:30,118 - __main__ - WARNING - Update "{'update_id': 79207678, 'inline_query': {'id': '6067064939609074911', 'query': '', 'offset': '', 'from': {'id': 1412598634, 'first_name': 'IVY', 'is_bot': False, 'username': 'I_01010110_Y', 'language_code': 'en'}}, '_effective_user': {'id': 1412598634, 'first_name': 'IVY', 'is_bot': False, 'username': 'I_01010110_Y', 'language_code': 'en'}}" caused error "0"
2021-03-19 14:34:33,152 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2021-03-19 14:34:33,788 - telegram.ext.updater - WARNING - Exiting immediately!
2021-03-19 14:37:13,783 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2021-03-19 14:37:14,037 - telegram.ext.updater - WARNING - Exiting immediately!
2021-03-19 14:37:54,290 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2021-03-19 14:37:54,636 - telegram.ext.updater - WARNING - Exiting immediately!
